spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/bitespeed}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: ${DATASOURCE_DRIVERCLASS:com.mysql.cj.jdbc.Driver}
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: ${SERVER_PORT:8080}
