spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lilfox
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
application:
  mainClass: IdentityreconciliationApplication
